'use strict'

const GAME_WIDTH = 1600
const GAME_HEIGHT = 900
const CENTER_X = GAME_WIDTH / 2
const CENTER_Y = GAME_HEIGHT / 2
const SIZE = 3
const BACKGROUND_COLOR = '#14bdac'
const PADDING = 200
const GRID_OUTLINE_COLOR = '#0da192'
const TEXT_COLOR = '#0a786d'
const X_COLOR = '#545454'
const O_COLOR = '#f2ebd3'
const CELL_WIDTH = Math.round(400 / SIZE)
const CELL_HEIGHT = Math.round(400 / SIZE)
module.exports = { GAME_WIDTH, GAME_HEIGHT, CELL_WIDTH, CELL_HEIGHT, BACKGROUND_COLOR,
	CENTER_X, CENTER_Y, SIZE, PADDING, GRID_OUTLINE_COLOR,
	X_COLOR, O_COLOR, TEXT_COLOR}